# domain=youtube.com proto=HTTPS/TLS1.2 rate=100% latency=285ms speed=3013kbps
NFQWS2_OPT="
--payload=tls_client_hello --lua-desync=fake:blob=0x00000000:badsum:repeats=1 --lua-desync=fakeddisorder:pos=midsld:badsum
"
